engine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('payment.urls', namespace='payments')),
]

payment/urls.py
from django.urls import path

from . import views

app_name = 'payments'

urlpatterns = [
    path('', views.payment_form_view, name='payment_form_view'),
    # path('red_to_check/', views.red_to_check, name='red_to_check'),
    # path('check/', views.send_check, name='send_check'),
    #
    # path('red_to_ext/'
    #      '<slug:order_no>&'
    #      '<slug:product_name>&'
    #      '<slug:product_count>&'
    #      '<slug:product_price>&'
    #      '<slug:total_sum>',
    #      views.red_to_ext, name='red_to_ext'),

]

payment/models.py
from django.db import models
import uuid


class Pay(models.Model):
    userName = models.CharField(max_length=10, default='client8')
    password = models.CharField(max_length=10, default='1762')
    # orderNumber = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    orderNumber = models.IntegerField(primary_key=True)
    amount = models.IntegerField()
    description = models.CharField(max_length=50)
    returnUrl = models.SlugField(default='/')

    def __str__(self):
        return self.description

payment/forms.py
from django import forms

from .models import Pay


class PayForm(forms.ModelForm):
    class Meta:
        model = Pay
        fields = ['description', 'amount']
        widgets = {
            'userName': forms.HiddenInput(),
            'password': forms.HiddenInput(),
            'orderNumber': forms.HiddenInput(),
            'returnUrl': forms.HiddenInput()
        }

payment/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse
import requests
import json

from .forms import PayForm


def payment_form_view(request):
    form = PayForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'form': form
    }

    return render(request, 'payment/index.html', context)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Payment{% endblock %}</title>
</head>
<body>

<h1>
    <a href="{% url 'payments:payment_form_view' %}" style="color: black; text-decoration: none;">
        -=Index=-
    </a>
</h1>

{% block content %}

{% endblock %}

</body>
</html>

templates/payment/abort.html
{% extends 'base.html' %}

{% block title %}
Abort
{% endblock %}

{% block content %}
<h2>Abort</h2>
{% endblock %}

templates/payment/check.html
{% extends 'base.html' %}

{% block title %}
    Check
{% endblock %}

{% block content %}
    <h2>Check</h2>

    <a href="{% url 'payments:send_check' %}" style="text-decoration: none; color: black; border: black 3px
        solid;">Submit</a>
    <a href="{% url 'payments:index' %}" style="text-decoration: none; color: black; border: black 3px
        solid;">Cancel</a>

{% endblock %}

templates/payment/index.html
{% extends 'base.html' %}

{% block title %}
    Index Page
{% endblock %}

{% block content %}

    <h2>Index Page</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Donate">
    </form>

{% endblock %}

templates/payment/success.html
{% extends 'base.html' %}

{% block title %}
Success
{% endblock %}

{% block content %}
<h2>Success</h2>
{% endblock %}